### ISSUE TITLE
Can't copy console output on windows when using start.bat

### ISSUE THREAD

**Issue by kapep** [LemoProject/Lemo-Data-Management-Server#25]
Calling "start java ..." in start.bat opens some kind of special console that does not show options to copy the output on Windows 8. Being able to copy the output would be useful when reporting bugs.

**Comment by kapep** [comment]
Quick fix (needs some testing): Start a new console with `cmd /C` to call java from a new standard console window. 

    START "Lemo" cmd /C "java -jar jetty-runner-8.1.9.v20130131.jar --classes ./conf --path lemo/apps lemo.war"
    @ECHO "Lemo starting ..."
    START "Lemo DMS" cmd /C "java -Xmx1024m -Xms512m -jar jetty-runner-8.1.9.v20130131.jar --port 8081 --classes ./conf/ --path lemo/dms lemo#dms.war"
    @ECHO "Lemo#dms starting ..."

As a bonus, this fix also adds nicer windows titles.

**Comment by sschwarzrock** [comment]
It does work that way. Fixed in start.bat
